language: java

notifications:
  slack: blackanthrax:eYnnaVzm0svyvQshJdIvokZM

script: build.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) 

deploy:
  provider: releases
  api_key: eYnnaVzm0svyvQshJdIvokZM
  file: target/pushnotifier-producer-spring-*.jar
  on:
    tags: true
