codecov:
  token: b04bf2fd-ff6e-43b6-b4a6-f57e092be8ba
  branch: master
  bot: null

  notify:
    slack:
      default:
        url: https://hooks.slack.com/services/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
        branches:
	  - master
        attachments: "sunburst, diff"

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        if_no_uploads: error

    patch:
      default:
        if_no_uploads: error

    changes: true


comment:
  layout: "header, diff, changes, suggestions"
  behavior: default
